### PR TITLE
Add support for GUI frames by w32

### PR DESCRIPTION
**Pull request by tak-kunihiro**
With minor revision, this package works for Emacs for MS-Windows.  I tested it for several weeks and works good for me. To include this patch, probably documentation should be revised as well.

### CODE REVIEW

**Comment by DarwinAwardWinner** [comment]
Does Emacs' actual Damon mode not work on Windows?

**Comment by tak-kunihiro** [comment]
Process icon is not shown up in task bar; thus there is no way to access to daemon. To have a frame using the daemon, one has to call `emacsclientw.exe --create-frame --no-wait'. It barely works but inconvenient as well as that on macOS.

**Comment by DarwinAwardWinner** [comment]
Isn't that the way Windows applications are supposed to work, though? When you close the last window, the application closes, and you open a new window by launching the application again. You're basically saying you want Emacs to work like a Mac app on Windows and stay open after closing the last window?

**Comment by DarwinAwardWinner** [comment]
Can you try out the w32-support branch? It incorporates your changes and makes some other fixes as well. I've left w32 support disabled by default, but there is now support for customizing it using `M-x customize-variable macpd-mac-frame-types`. Just check the w32 checkbox and save the value.

**Comment by tak-kunihiro** [comment]
Yes, I want to keep Emacs alive even after closing the last frame.  Thank you for the organization and make a new branch.  It works good besides line 123 and 125 of mac-pseudo-daemon.el in w32-branch.  `null' at line 123 needs one argument and `signal' at line 125 accepts only two arguments.  Can you fix it? TIA

**Comment by DarwinAwardWinner** [comment]
Ok, fixed. Looks like I forgot to finish writing that function. Thanks for spotting that.

**Comment by DarwinAwardWinner** [comment]
For future reference, you don't need to close issues yourself. They will be closed automatically when I merge the commit that fixes them into the master branch.

**Comment by tak-kunihiro** [comment]
Thank you to let me know!

**Pull request closed without merging**
